### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by florian262000**

### CODE REVIEW

**Comment by SteveMcT** [comment]
This commit is empty.

**Comment by gebes** [comment]
I understand @SteveMcT if the changes are hard to review. Take your time.

**Comment by SteveMcT** [comment]
@Gebes Sarcasm has increased to 42

**Comment by gebes** [comment]
I like that number. 
Just approve the changes. These will improve the game :D

**Comment by gebes** [comment]
Awesome!

**Pull request merged**
